pipeline {
    agent {
        node {
            label 'master'
        }
    }
    stages {
        stage('terraform started') {
            steps {
                sh 'echo "Started...!" '
            }
        }
        stage('git clone') {
            steps {
                sh 'sudo rm -r *;sudo git clone https://github.com/balajircs02/testing.git'
            }
        }
        stage('tfsvars create'){
            steps {
                sh 'sudo cp /DemoProject/ws/terraform/variables.tf ./jenkins/'
            }
        }
        stage('terraform init') {
            steps {
                sh 'sudo /DemoProject/ws/terraform init ./jenkins'
            }
        }
        stage('terraform plan') {
            steps {
                sh 'ls ./jenkins; sudo /DemoProject/ws/terraform plan ./jenkins'
            }
        }
        stage('terraform ended') {
            steps {
                sh 'echo "Ended....!!"'
            }
        }
      
    }
}
